[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Swedish URL redirects
[[redirects]]
  from = "/om-oss"
  to = "/about"
  status = 301
  
[[redirects]]
  from = "/privacy"
  to = "/integritetspolicy"
  status = 301

[[redirects]]
  from = "/terms"
  to = "/anvandardvillkor"
  status = 301

# Ensure SPA routing works for Swedish URLs
[[redirects]]
  from = "/integritetspolicy"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/anvandardvillkor" 
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  SITE_NAME = "Massage Corner Sverige AB"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=86400"